# Generated by Django 2.1.7 on 2019-03-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tdlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('cr_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_check', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
