# Generated by Django 2.1.7 on 2019-03-21 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('post_addr', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(blank=True, max_length=20)),
                ('invoice_date', models.DateField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contract_num', models.CharField(blank=True, max_length=20)),
                ('contract_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Payer'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='payer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Payer'),
        ),
    ]
